min_trimmed_length = 6
min_word_count = 5
max_word_count = 10
min_characters = 3
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = false
needs_uppercase_start = false
disallowed_symbols = [
  '<', '>', '+', '*', '\', '#', '@', '^', '[', ']', '(', ')', '/', '=',
  'Å', 'Ł', 'ś', 'ń', 'ź', 'ñ', 'š', 'ö', 'â', 'ë', 'ä', 'ê', 
  'α', 'β', 'Γ', 'γ', 'Δ', 'δ', 'ε', 'ζ', 'η', 'Θ', 'θ', 'ι', 'κ',
  'Λ', 'λ', 'μ', 'ν', 'Ξ', 'ξ', 'Π', 'π', 'ρ', 'Σ', 'σ', 'ς', 'τ',
  'υ', 'Φ', 'φ', 'χ', 'Ψ', 'ψ', 'Ω', 'ω',
  'ム', 'בְ', 'ɛ', 'ɔ',
  '$', '€', 
  'б', 'м', 'ы', 'л',
  '"', '«', '»', '“', '”', '„', '“', '•', '‘'
]
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]
abbreviation_patterns = [
  "[A-Z][A-Z]+",
  "[A-Z]+\\.* ?[A-Z]",
  "adib\\.",
  "K\\. o\\.|K\\. a\\.|adib\\. ",
  "[;,]$"
  ]
