replacements = [
  ["z.B.", "zum Beispiel"],
  ["z. B.", "zum Beispiel"],
  ["ca.", "circa"],
  ["bzw.", "beziehungsweise"],
  ["gem.", "gemäß"],
  ["sog.", "sogenannt"],
  ["Art.", "Artikel"],
  ["geb.", "geboren"],
  ["allg.", "allgemein"],
  ["bes.", "besonders"],
  ["bez.", "bezüglich"],
  ["eigtl.", "eigentlich"],
  ["gegr.", "gegründet"],
  ["ugs.", "umgangssprachlich"],
  ["urspr.", "ursprünglich"],
  ["usw.", "und so weiter"],
  ["zz.", "zurzeit"],
  ["ggf.", "gegebenenfalls"],
  ["bspw.", "beispielsweise"],
  ["mind.", "mindestens"],
  ["evtl.", "eventuell"],
  ["bzgl.", "bezüglich"],
]

segmenter = "python"
min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_characters = 2
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = true
allowed_symbols_regex = "[\u0020A-Za-zäöüßÄÖÜ\"„“‚‘’–\\.?!()]"
disallowed_symbols = []
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]
even_symbols = ['"']

matching_symbols = [
  ["„", "“"],
  ["(", ")"]
]

# Abbreviations
#   - Jahrhundert and others at the beginning of the sentence (circumvents wrongly splitted such as "Im 3. Jahrhundert begann ...")
#   - A.B, z.B., or SMS
abbreviation_patterns = [
  "^(Jahrhundert|Liga|Bundesliga|Klasse)",
  "[A-Z]+\\.*[A-Z]",
]

# Other patterns
#   - Sentence delimiter can only be at the end of a sentence. This also takes care of abbreviations.
#   - No words with only one letter (" a.", " a", " a ", "a ")
#   - Mixed upper/lowercase in words (LaSi - mostly chemical elements?)
other_patterns = [
  "[\\.|\\?|!].+$",
  "(\\s[A-Za-z]{1}[\\.|\\?|!]*$)|(^[A-Za-z]{1}\\s)|\\s[A-Za-z]{1}\\s",
  "[a-z][A-Z][a-z]",
]
