min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_characters = 2
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = true
allowed_symbols_regex = "[\u0020-\u007BäöüßÄÖÜ„“‚‘’–\\.]"
disallowed_symbols = []
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]

matching_symbols = [
  ["„", "“"]
]

