min_trimmed_length = 3
min_word_count = 1
max_word_count = 14
min_characters = 1
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = false
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]

allowed_symbols_regex = "[\u0020A-Za-z\"„“‚‘’–\\.?!()]"
even_symbols = ['"']
matching_symbols = [
  ["„", "“"],
  ["(", ")"]
]

abbreviation_patterns = [
  "[A-Z]+\\.*[A-Z]"
]

other_patterns = []
