min_trimmed_length = 3
min_word_count = 4
max_word_count = 14
min_characters = 2
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = true
needs_uppercase_start = true
disallowed_symbols = [
  'q', 'w', 'x', 'y','<', '>', '+', '*', '\', '#', '@', '^', '[', ']', '(', ')', '/',
  'ä', 'ö', 'ü', 'ß','ð','ð',
  'À','Á','Â','Ã','Ä','Å','Æ','Ç','È','É','Ê','Ë','Ì','Í','Î','Ï','Ð','Ñ','Ò','Ó','Ô','Õ','Ö','Ø','Ù','Ú','Û','Û','Ü','Ý',
  'à','á','â','ã','å','æ','ç','è','é','ê','ë','ì','í','î','ï','ð','ñ','ò','ó','ô','õ',
  'ø','ù','ú','û','ý','þ','ÿ',
  'ā','ă','ą','ć','ċ','č','ď','đ','ē','ĕ','ė','ę','ě','ğ','ġ','ģ','ħ','ĩ','ī','ĭ','į','ı','ķ','ĸ','ĺ','ļ',
  'ľ','ŀ','ł','ń','ņ','ņ','ṫ','š','Ў',
  'ḃ','ḋ','ḟ','ṁ','ṗ','ṡ','ẁ','ẃ','ẅ','ẛ','ỳ',
  'α', 'β', 'Γ', 'γ', 'Δ', 'δ', 'ε', 'ζ', 'η', 'Θ', 'θ', 'ι', 'κ',
  'Λ', 'λ', 'μ', 'ν', 'Ξ', 'ξ', 'Π', 'π', 'ρ', 'Σ', 'σ', 'ς', 'τ',
  'υ', 'Φ', 'φ', 'χ', 'Ψ', 'ψ', 'Ω', 'ω',
]
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]

# Abbreviation examples for each regex, also cheating a bit and adding more regex which has nothing to do with abbreviations:
#   - No words with only one letter (" a.", " a", " a ", "a ")
#   - Mixed upper/lowercase in words (LaSi - mostly chemical elements?)
abbreviation_patterns = [
  "[A-Z]+\\.*[A-Z]",
  "ktp\\.|ekz\\.|ca\\.|gem\\.|[a|p]\\.\\sK\\.|Prof\\.|Ak\\.|anst\\.|bv\\.|k\\.|k\\.a\\.|k\\.c\\.|p\\.|v\\.|ĉ\\.|i\\.a\\.|t\\.n\\.|t\\.e\\.",
  "(\\s[A-Za-z]{1}[\\.|\\?|!]*$)|(^[A-Za-z]{1}\\s)|\\s[A-Za-z]{1}\\s",
  "[a-z][A-Z][a-z]",
]
