min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_characters = 2
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = true
disallowed_symbols = ['<', '>', '+', '*', '\', '#', '@', '^', '[', ']', '(', ')', '/', 'μ']
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]

# Abbreviation examples for each regex:
#   - A.B oder z.B.
#   - Satzbeginn mit "B. ..."
#   - Satzende mit nur einem Buchstaben am Ende "... z."
#   - Jahrhundert an Satzbeginn (umgeht Fehler mit WikiExtractor wie z.B. "Im 3. Jahrhundert begann ..." was zu 2 unvollständigen Sätzen führt)
#   - bzw. / ca. / gem. / v. Chr. / n. Chr.
abbreviation_patterns = [
  "[A-Z]+\\.*[A-Z]",
  "^[A-Za-z]{1}\\.",
  "\\s[A-Za-z]{1}\\.$",
  "^Jahrhundert",
  "bzw\\.|ca\\.|gem\\.|[v|n]\\.\\sChr\\.",
]
