min_trimmed_length = 0
min_word_count = 0
max_word_count = 50
min_characters = 0
may_end_with_colon = false
quote_start_with_letter = false
needs_punctuation_end = false
needs_letter_start = false
needs_uppercase_start = false
matching_symbols = [
  ["ред", "."]
]
replacements = [
  ["ред", "."]
]
disallowed_symbols = [
  'a', 'e', 'i', 'o',
]
abbreviation_patterns = ["[A-Z]+\\.*[A-Z]"]
