min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_characters = 1
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = true
allowed_symbols_regex = "[0-9A-Za-záÁéÉíÍóÓöÖőŐúÚüÜ„“‚‘’ –\\.?!]"
disallowed_symbols = []
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]

matching_symbols = [
  ["„", "“"]
]

abbreviation_patterns = [
  "ún\\.|ref\\.|[Rr]\\. kath\\.|vm\\.|stb\\.|ill\\.|pl\\.|Bt\\.|Kft\\.|Kht\\.|vhr\\.|tsz\\.|Zrt\\.|Nyrt\\.|Rt\\.|KKT\\.|Mo\\.|Bp\\.|Özv\\.|Korm\\.|Kr\\. ?e\\.|Kr\\. ?u\\.|[MDCLXVI]+\\.|BSc\\.|MSc\\.|Dr\\.|Phd\\.|ltp\\.|vb\\.|km\\.|nm\\.|dm\\.|mg\\.|KW\\.|W\\.|kb\\.|sz\\." ,
]