segmenter = "python"

min_trimmed_length = 2
min_word_count = 3
max_word_count = 14
min_characters = 2
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = true
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;", " :", "( ", " )"]
allowed_symbols_regex = "[a-ząćęłńóśżźA-ZĄĆĘŁŃÓŚŻŹ ,.?!:\\-–—\"'„“”]"

# Trimm out all abbrevation which can be misread or not known by reader
abbreviation_patterns = [
  "[A-ZĄĆĘŁŃÓŚŻŹ]{2,}",
  "(?i)\\s[a-ząćęłńóśżź]{1,3}\\. ?[a-ząćęłńóśżź]",
  # Abbrevations without a period  
  "(?i) (bp|dr|nr|mgr|mjr|płk|wg|dra)\\.? "  
]

# Mixed upper/lowercase in words (LaSi - mostly chemical elements?)
other_patterns = [ 
  "[a-z][A-Z][a-z]",
]

# Replace known abbrevations and other items when only one 
# way to read it or has one valid form
replacements = [
  ["p.n.e.", "przed naszą erą"],
  ["n.e.", "naszej ery"],
  ["n.p.m.", "nad poziomem morza"],
  ["np. ", "na przykład "],
  ["n.p. ", "na przykład "],
  ["tj. ", "to jest "],
  ["m.in. ", "między innymi "],
  [" im. ", " imienia "],
  ["tzn. ", "to znaczy "],  
  ["przy ul. ", "przy ulicy "],
  ["ul. ", "ulica "],
  ["ok. ", "około "],
  ["jw. ", "jak wyżej "],
  ["ds. ", "do spraw "],  
  [" mgra ", " magistra "],
  [" w pow. ", " w powiecie "],
  [" w tzw. ", " w tak zwanym "],
  [" tzw. ", " tak zwany "],
  # Centuries
  ["w XXXIX wieku", "w trzydziestym dziewiątym wieku"], 
  ["W XXXIX wieku", "W trzydziestym dziewiątym wieku"], 
  ["XXXIX wieku", "trzydziestego dziewiątego wieku"], 
  ["XXXIX wiek", "trzydziesty dziewiąty wiek"], 
  ["oniec XXXIX w.", "oniec trzydziestego dziewiątego wieku"], 
  ["końca XXXIX w.", "końca trzydziestego dziewiątego wieku"], 
  ["oczątek XXXIX w.", "oczątek trzydziestego dziewiątego wieku"], 
  ["początku XXXIX w.", "początku trzydziestego dziewiątego wieku"], 
  ["w XXXVIII wieku", "w trzydziestym ósmym wieku"], 
  ["W XXXVIII wieku", "W trzydziestym ósmym wieku"], 
  ["XXXVIII wieku", "trzydziestego ósmego wieku"], 
  ["XXXVIII wiek", "trzydziesty ósmy wiek"], 
  ["oniec XXXVIII w.", "oniec trzydziestego ósmego wieku"], 
  ["końca XXXVIII w.", "końca trzydziestego ósmego wieku"], 
  ["oczątek XXXVIII w.", "oczątek trzydziestego ósmego wieku"], 
  ["początku XXXVIII w.", "początku trzydziestego ósmego wieku"], 
  ["w XXXVII wieku", "w trzydziestym siódmym wieku"], 
  ["W XXXVII wieku", "W trzydziestym siódmym wieku"], 
  ["XXXVII wieku", "trzydziestego siódmego wieku"], 
  ["XXXVII wiek", "trzydziesty siódmy wiek"], 
  ["oniec XXXVII w.", "oniec trzydziestego siódmego wieku"], 
  ["końca XXXVII w.", "końca trzydziestego siódmego wieku"], 
  ["oczątek XXXVII w.", "oczątek trzydziestego siódmego wieku"], 
  ["początku XXXVII w.", "początku trzydziestego siódmego wieku"], 
  ["w XXXVI wieku", "w trzydziestym szóstym wieku"], 
  ["W XXXVI wieku", "W trzydziestym szóstym wieku"], 
  ["XXXVI wieku", "trzydziestego szóstego wieku"], 
  ["XXXVI wiek", "trzydziesty szósty wiek"], 
  ["oniec XXXVI w.", "oniec trzydziestego szóstego wieku"], 
  ["końca XXXVI w.", "końca trzydziestego szóstego wieku"], 
  ["oczątek XXXVI w.", "oczątek trzydziestego szóstego wieku"], 
  ["początku XXXVI w.", "początku trzydziestego szóstego wieku"], 
  ["w XXXV wieku", "w trzydziestym piątym wieku"], 
  ["W XXXV wieku", "W trzydziestym piątym wieku"], 
  ["XXXV wieku", "trzydziestego piątego wieku"], 
  ["XXXV wiek", "trzydziesty piąty wiek"], 
  ["oniec XXXV w.", "oniec trzydziestego piątego wieku"], 
  ["końca XXXV w.", "końca trzydziestego piątego wieku"], 
  ["oczątek XXXV w.", "oczątek trzydziestego piątego wieku"], 
  ["początku XXXV w.", "początku trzydziestego piątego wieku"], 
  ["w XXXIV wieku", "w trzydziestym czwartym wieku"], 
  ["W XXXIV wieku", "W trzydziestym czwartym wieku"], 
  ["XXXIV wieku", "trzydziestego czwartego wieku"], 
  ["XXXIV wiek", "trzydziesty czwarty wiek"], 
  ["oniec XXXIV w.", "oniec trzydziestego czwartego wieku"], 
  ["końca XXXIV w.", "końca trzydziestego czwartego wieku"], 
  ["oczątek XXXIV w.", "oczątek trzydziestego czwartego wieku"], 
  ["początku XXXIV w.", "początku trzydziestego czwartego wieku"], 
  ["w XXXIII wieku", "w trzydziestym trzecim wieku"], 
  ["W XXXIII wieku", "W trzydziestym trzecim wieku"], 
  ["XXXIII wieku", "trzydziestego trzeciego wieku"], 
  ["XXXIII wiek", "trzydziesty trzeci wiek"], 
  ["oniec XXXIII w.", "oniec trzydziestego trzeciego wieku"], 
  ["końca XXXIII w.", "końca trzydziestego trzeciego wieku"], 
  ["oczątek XXXIII w.", "oczątek trzydziestego trzeciego wieku"], 
  ["początku XXXIII w.", "początku trzydziestego trzeciego wieku"], 
  ["w XXXII wieku", "w trzydziestym drugim wieku"], 
  ["W XXXII wieku", "W trzydziestym drugim wieku"], 
  ["XXXII wieku", "trzydziestego drugiego wieku"], 
  ["XXXII wiek", "trzydziesty drugi wiek"], 
  ["oniec XXXII w.", "oniec trzydziestego drugiego wieku"], 
  ["końca XXXII w.", "końca trzydziestego drugiego wieku"], 
  ["oczątek XXXII w.", "oczątek trzydziestego drugiego wieku"], 
  ["początku XXXII w.", "początku trzydziestego drugiego wieku"], 
  ["w XXXI wieku", "w trzydziestym pierwszym wieku"], 
  ["W XXXI wieku", "W trzydziestym pierwszym wieku"], 
  ["XXXI wieku", "trzydziestego pierwszego wieku"], 
  ["XXXI wiek", "trzydziesty pierwszy wiek"], 
  ["oniec XXXI w.", "oniec trzydziestego pierwszego wieku"], 
  ["końca XXXI w.", "końca trzydziestego pierwszego wieku"], 
  ["oczątek XXXI w.", "oczątek trzydziestego pierwszego wieku"], 
  ["początku XXXI w.", "początku trzydziestego pierwszego wieku"], 
  ["w XXX wieku", "w trzydziestym wieku"], 
  ["W XXX wieku", "W trzydziestym wieku"], 
  ["XXX wieku", "trzydziestego wieku"], 
  ["XXX wiek", "trzydziesty wiek"], 
  ["oniec XXX w.", "oniec trzydziestego wieku"], 
  ["końca XXX w.", "końca trzydziestego wieku"], 
  ["oczątek XXX w.", "oczątek trzydziestego wieku"], 
  ["początku XXX w.", "początku trzydziestego wieku"], 
  ["w XXIX wieku", "w dwudziestym dziewiątym wieku"], 
  ["W XXIX wieku", "W dwudziestym dziewiątym wieku"], 
  ["XXIX wieku", "dwudziestego dziewiątego wieku"], 
  ["XXIX wiek", "dwudziesty dziewiąty wiek"], 
  ["oniec XXIX w.", "oniec dwudziestego dziewiątego wieku"], 
  ["końca XXIX w.", "końca dwudziestego dziewiątego wieku"], 
  ["oczątek XXIX w.", "oczątek dwudziestego dziewiątego wieku"], 
  ["początku XXIX w.", "początku dwudziestego dziewiątego wieku"], 
  ["w XXVIII wieku", "w dwudziestym ósmym wieku"], 
  ["W XXVIII wieku", "W dwudziestym ósmym wieku"], 
  ["XXVIII wieku", "dwudziestego ósmego wieku"], 
  ["XXVIII wiek", "dwudziesty ósmy wiek"], 
  ["oniec XXVIII w.", "oniec dwudziestego ósmego wieku"], 
  ["końca XXVIII w.", "końca dwudziestego ósmego wieku"], 
  ["oczątek XXVIII w.", "oczątek dwudziestego ósmego wieku"], 
  ["początku XXVIII w.", "początku dwudziestego ósmego wieku"], 
  ["w XXVII wieku", "w dwudziestym siódmym wieku"], 
  ["W XXVII wieku", "W dwudziestym siódmym wieku"], 
  ["XXVII wieku", "dwudziestego siódmego wieku"], 
  ["XXVII wiek", "dwudziesty siódmy wiek"], 
  ["oniec XXVII w.", "oniec dwudziestego siódmego wieku"], 
  ["końca XXVII w.", "końca dwudziestego siódmego wieku"], 
  ["oczątek XXVII w.", "oczątek dwudziestego siódmego wieku"], 
  ["początku XXVII w.", "początku dwudziestego siódmego wieku"], 
  ["w XXVI wieku", "w dwudziestym szóstym wieku"], 
  ["W XXVI wieku", "W dwudziestym szóstym wieku"], 
  ["XXVI wieku", "dwudziestego szóstego wieku"], 
  ["XXVI wiek", "dwudziesty szósty wiek"], 
  ["oniec XXVI w.", "oniec dwudziestego szóstego wieku"], 
  ["końca XXVI w.", "końca dwudziestego szóstego wieku"], 
  ["oczątek XXVI w.", "oczątek dwudziestego szóstego wieku"], 
  ["początku XXVI w.", "początku dwudziestego szóstego wieku"], 
  ["w XXV wieku", "w dwudziestym piątym wieku"], 
  ["W XXV wieku", "W dwudziestym piątym wieku"], 
  ["XXV wieku", "dwudziestego piątego wieku"], 
  ["XXV wiek", "dwudziesty piąty wiek"], 
  ["oniec XXV w.", "oniec dwudziestego piątego wieku"], 
  ["końca XXV w.", "końca dwudziestego piątego wieku"], 
  ["oczątek XXV w.", "oczątek dwudziestego piątego wieku"], 
  ["początku XXV w.", "początku dwudziestego piątego wieku"], 
  ["w XXIV wieku", "w dwudziestym czwartym wieku"], 
  ["W XXIV wieku", "W dwudziestym czwartym wieku"], 
  ["XXIV wieku", "dwudziestego czwartego wieku"], 
  ["XXIV wiek", "dwudziesty czwarty wiek"], 
  ["oniec XXIV w.", "oniec dwudziestego czwartego wieku"], 
  ["końca XXIV w.", "końca dwudziestego czwartego wieku"], 
  ["oczątek XXIV w.", "oczątek dwudziestego czwartego wieku"], 
  ["początku XXIV w.", "początku dwudziestego czwartego wieku"], 
  ["w XXIII wieku", "w dwudziestym trzecim wieku"], 
  ["W XXIII wieku", "W dwudziestym trzecim wieku"], 
  ["XXIII wieku", "dwudziestego trzeciego wieku"], 
  ["XXIII wiek", "dwudziesty trzeci wiek"], 
  ["oniec XXIII w.", "oniec dwudziestego trzeciego wieku"], 
  ["końca XXIII w.", "końca dwudziestego trzeciego wieku"], 
  ["oczątek XXIII w.", "oczątek dwudziestego trzeciego wieku"], 
  ["początku XXIII w.", "początku dwudziestego trzeciego wieku"], 
  ["w XXII wieku", "w dwudziestym drugim wieku"], 
  ["w XXII wieku", "W dwudziestym drugim wieku"], 
  ["XXII wieku", "dwudziestego drugiego wieku"], 
  ["XXII wiek", "dwudziesty drugi wiek"], 
  ["oniec XXII w.", "oniec dwudziestego drugiego wieku"], 
  ["końca XXII w.", "końca dwudziestego drugiego wieku"], 
  ["oczątek XXII w.", "oczątek dwudziestego drugiego wieku"], 
  ["początku XXII w.", "początku dwudziestego drugiego wieku"], 
  ["w XXI wieku", "w dwudziestym pierwszym wieku"], 
  ["W XXI wieku", "W dwudziestym pierwszym wieku"], 
  ["XXI wieku", "dwudziestego pierwszego wieku"], 
  ["XXI wiek", "dwudziesty pierwszy wiek"], 
  ["oniec XXI w.", "oniec dwudziestego pierwszego wieku"], 
  ["końca XXI w.", "końca dwudziestego pierwszego wieku"], 
  ["oczątek XXI w.", "oczątek dwudziestego pierwszego wieku"], 
  ["początku XXI w.", "początku dwudziestego pierwszego wieku"], 
  ["w XX wieku", "w dwudziestym wieku"], 
  ["W XX wieku", "W dwudziestym wieku"], 
  ["XX wieku", "dwudziestego wieku"], 
  ["XX wiek", "dwudziesty wiek"], 
  ["oniec XX w.", "oniec dwudziestego wieku"], 
  ["końca XX w.", "końca dwudziestego wieku"], 
  ["oczątek XX w.", "oczątek dwudziestego wieku"], 
  ["początku XX w.", "początku dwudziestego wieku"], 
  ["w XIX wieku", "w dziewiętnastym wieku"], 
  ["W XIX wieku", "W dziewiętnastym wieku"], 
  ["XIX wieku", "dziewiętnastego wieku"], 
  ["XIX wiek", "dziewiętnasty wiek"], 
  ["oniec XIX w.", "oniec dziewiętnastego wieku"], 
  ["końca XIX w.", "końca dziewiętnastego wieku"], 
  ["oczątek XIX w.", "oczątek dziewiętnastego wieku"], 
  ["początku XIX w.", "początku dziewiętnastego wieku"], 
  ["w XVIII wieku", "w osiemnastym wieku"], 
  ["W XVIII wieku", "W osiemnastym wieku"], 
  ["XVIII wieku", "osiemnastego wieku"], 
  ["XVIII wiek", "osiemnasty wiek"], 
  ["oniec XVIII w.", "oniec osiemnastego wieku"], 
  ["końca XVIII w.", "końca osiemnastego wieku"], 
  ["oczątek XVIII w.", "oczątek osiemnastego wieku"], 
  ["początku XVIII w.", "początku osiemnastego wieku"], 
  ["w XVII wieku", "w siedemnastym wieku"], 
  ["W XVII wieku", "W siedemnastym wieku"], 
  ["XVII wieku", "siedemnastego wieku"], 
  ["XVII wiek", "siedemnasty wiek"], 
  ["oniec XVII w.", "oniec siedemnastego wieku"], 
  ["końca XVII w.", "końca siedemnastego wieku"], 
  ["oczątek XVII w.", "oczątek siedemnastego wieku"], 
  ["początku XVII w.", "początku siedemnastego wieku"], 
  ["w XVI wieku", "w szesnastym wieku"], 
  ["W XVI wieku", "W szesnastym wieku"], 
  ["XVI wieku", "szesnastego wieku"], 
  ["XVI wiek", "szesnasty wiek"], 
  ["oniec XVI w.", "oniec szesnastego wieku"], 
  ["końca XVI w.", "końca szesnastego wieku"], 
  ["oczątek XVI w.", "oczątek szesnastego wieku"], 
  ["początku XVI w.", "początku szesnastego wieku"], 
  ["w XV wieku", "w piętnastym wieku"], 
  ["W XV wieku", "W piętnastym wieku"], 
  ["XV wieku", "piętnastego wieku"], 
  ["XV wiek", "piętnasty wiek"], 
  ["oniec XV w.", "oniec piętnastego wieku"], 
  ["końca XV w.", "końca piętnastego wieku"], 
  ["oczątek XV w.", "oczątek piętnastego wieku"], 
  ["początku XV w.", "początku piętnastego wieku"], 
  ["w XIV wieku", "w czternastym wieku"], 
  ["W XIV wieku", "W czternastym wieku"], 
  ["XIV wieku", "czternastego wieku"], 
  ["XIV wiek", "czternasty wiek"], 
  ["oniec XIV w.", "oniec czternastego wieku"], 
  ["końca XIV w.", "końca czternastego wieku"], 
  ["oczątek XIV w.", "oczątek czternastego wieku"], 
  ["początku XIV w.", "początku czternastego wieku"], 
  ["w XIII wieku", "w trzynastym wieku"], 
  ["W XIII wieku", "W trzynastym wieku"], 
  ["XIII wieku", "trzynastego wieku"], 
  ["XIII wiek", "trzynasty wiek"], 
  ["oniec XIII w.", "oniec trzynastego wieku"], 
  ["końca XIII w.", "końca trzynastego wieku"], 
  ["oczątek XIII w.", "oczątek trzynastego wieku"], 
  ["początku XIII w.", "początku trzynastego wieku"], 
  ["w XII wieku", "w dwunastym wieku"], 
  ["W XII wieku", "W dwunastym wieku"], 
  ["XII wieku", "dwunastego wieku"], 
  ["XII wiek", "dwunasty wiek"], 
  ["oniec XII w.", "oniec dwunastego wieku"], 
  ["końca XII w.", "końca dwunastego wieku"], 
  ["oczątek XII w.", "oczątek dwunastego wieku"], 
  ["początku XII w.", "początku dwunastego wieku"], 
  ["w XI wieku", "w jedenastym wieku"], 
  ["W XI wieku", "W jedenastym wieku"], 
  ["XI wieku", "jedenastego wieku"], 
  ["XI wiek", "jedenasty wiek"], 
  ["oniec XI w.", "oniec jedenastego wieku"], 
  ["końca XI w.", "końca jedenastego wieku"], 
  ["oczątek XI w.", "oczątek jedenastego wieku"], 
  ["początku XI w.", "początku jedenastego wieku"], 
  ["w X wieku", "w dziesiątym wieku"], 
  ["W X wieku", "W dziesiątym wieku"], 
  ["X wieku", "dziesiątego wieku"], 
  ["X wiek", "dziesiąty wiek"], 
  ["oniec X w.", "oniec dziesiątego wieku"], 
  ["końca X w.", "końca dziesiątego wieku"], 
  ["oczątek X w.", "oczątek dziesiątego wieku"], 
  ["początku X w.", "początku dziesiątego wieku"], 
  ["w IX wieku", "w dziewiątym wieku"], 
  ["W IX wieku", "W dziewiątym wieku"], 
  ["IX wieku", "dziewiątego wieku"], 
  ["IX wiek", "dziewiąty wiek"], 
  ["oniec IX w.", "oniec dziewiątego wieku"], 
  ["końca IX w.", "końca dziewiątego wieku"], 
  ["oczątek IX w.", "oczątek dziewiątego wieku"], 
  ["początku IX w.", "początku dziewiątego wieku"], 
  ["w VIII wieku", "w ósmym wieku"], 
  ["W VIII wieku", "W ósmym wieku"], 
  ["VIII wieku", "ósmego wieku"], 
  ["VIII wiek", "ósmy wiek"], 
  ["oniec VIII w.", "oniec ósmego wieku"], 
  ["końca VIII w.", "końca ósmego wieku"], 
  ["oczątek VIII w.", "oczątek ósmego wieku"], 
  ["początku VIII w.", "początku ósmego wieku"], 
  ["w VII wieku", "w siódmym wieku"], 
  ["W VII wieku", "W siódmym wieku"], 
  ["VII wieku", "siódmego wieku"], 
  ["VII wiek", "siódmy wiek"], 
  ["oniec VII w.", "oniec siódmego wieku"], 
  ["końca VII w.", "końca siódmego wieku"], 
  ["oczątek VII w.", "oczątek siódmego wieku"], 
  ["początku VII w.", "początku siódmego wieku"], 
  ["w VI wieku", "w szóstym wieku"], 
  ["W VI wieku", "W szóstym wieku"], 
  ["VI wieku", "szóstego wieku"], 
  ["VI wiek", "szósty wiek"], 
  ["oniec VI w.", "oniec szóstego wieku"], 
  ["końca VI w.", "końca szóstego wieku"], 
  ["oczątek VI w.", "oczątek szóstego wieku"], 
  ["początku VI w.", "początku szóstego wieku"], 
  ["w V wieku", "w piątym wieku"], 
  ["W V wieku", "W piątym wieku"], 
  ["V wieku", "piątego wieku"], 
  ["V wiek", "piąty wiek"], 
  ["oniec V w.", "oniec piątego wieku"], 
  ["końca V w.", "końca piątego wieku"], 
  ["oczątek V w.", "oczątek piątego wieku"], 
  ["początku V w.", "początku piątego wieku"], 
  ["w IV wieku", "w czwartym wieku"], 
  ["W IV wieku", "W czwartym wieku"], 
  ["IV wieku", "czwartego wieku"], 
  ["IV wiek", "czwarty wiek"], 
  ["oniec IV w.", "oniec czwartego wieku"], 
  ["końca IV w.", "końca czwartego wieku"], 
  ["oczątek IV w.", "oczątek czwartego wieku"], 
  ["początku IV w.", "początku czwartego wieku"], 
  ["w III wieku", "w trzecim wieku"], 
  ["W III wieku", "W trzecim wieku"], 
  ["III wieku", "trzeciego wieku"], 
  ["III wiek", "trzeci wiek"], 
  ["oniec III w.", "oniec trzeciego wieku"], 
  ["końca III w.", "końca trzeciego wieku"], 
  ["oczątek III w.", "oczątek trzeciego wieku"], 
  ["początku III w.", "początku trzeciego wieku"], 
  ["w II wieku", "w drugim wieku"], 
  ["W II wieku", "W drugim wieku"], 
  ["II wieku", "drugiego wieku"], 
  ["II wiek", "drugi wiek"], 
  ["oniec II w.", "oniec drugiego wieku"], 
  ["końca II w.", "końca drugiego wieku"], 
  ["oczątek II w.", "oczątek drugiego wieku"], 
  ["początku II w.", "początku drugiego wieku"], 
  ["w I wieku", "w pierwszym wieku"], 
  ["W I wieku", "W pierwszym wieku"], 
  ["I wieku", "pierwszego wieku"], 
  ["I wiek", "pierwszy wiek"], 
  ["oniec I w.", "oniec pierwszego wieku"], 
  ["końca I w.", "końca pierwszego wieku"], 
  ["oczątek I w.", "oczątek pierwszego wieku"], 
  ["początku I w.", "początku pierwszego wieku"]
]

matching_symbols = [
  ["„", "“"],
  ["(", ")"],
  ["[", "]"]
]

