min_trimmed_length = 3

# For count = 2 we have sentences like: "Это он", "Будет беда"
# and a lot of trash abbreviations like "до н.", "и доп."
min_word_count = 3

max_word_count = 14

# In Russian, words can consist of one letter, so no restrictions
min_characters = 0

may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true

# Apparently, in some places the sentences are cut incorrectly,
# which is why we get some part of the sentence, and not its entirety.
# This is required to fix sentences like:
# с Иваном Галамяном.
needs_uppercase_start = true

# The following are symbols that are either absent in the Russian language
# or participating in language constructs that will be difficult or impossible to voice,
# as well as constructions causing problems in sentences
# (for example, opening quotes without closing)
disallowed_symbols = [
  '<', '>', '+', '*', '\', '#', '@', '^', '[', ']', '(', ')', '/',
  'é', 'è', 'à', 'ç', 'Å', '薛', '⋅', '·', 'ѿ', '=', '|', '≡', '→',
  '×', 'Ա', 'բ', 'դ', 'ի', 'ս', 'յ', 'շ', 'ո', '•', 'थ्', '©', '¸',
  '天', '不', '言', '，', '以', '行', '與', '事', '示', '之', '而',
  '已', '矣', '《', '大', '学', '集', '注', '》', '多', '识', '录',
  '「', '鴃', '」', '鳩', '鳧', '鶯', 'ا', 'ل', 'ر', 'د', 'ن',
  'เ', 'วฺ', 'ส', 'ลฺ', 'ยุ', 'ทิ', 'โ', 'ร', 'ชฺ', 'ท', 'ยุ', 'ตฺ', 'สฺ',
  'ย', 'พ', 'ทฺ', 'นิ', 'इ', '_', 'Ѳ', '‹', '›', '`',
  'і', 'ў', '~', '®', '%', '⟨', '⟩', '¬', '&', '≤',
  'α', 'β', 'Γ', 'γ', 'Δ', 'δ', 'ε', 'ζ', 'η', 'Θ', 'θ', 'ι', 'Ә',
  'Λ', 'λ', 'μ', 'ν', 'Ξ', 'ξ', 'ρ', 'Σ', 'σ', 'ς', 'τ',
  'υ', 'Φ', 'φ', 'χ', 'Ψ', 'ψ', 'Ω', 'ω', 'a', 'A', 'b', 'B', 'c',
  'C', 'd', 'D', 'e', 'E', 'f', 'F', 'g', 'G', 'h', 'H', 'i', 'I',
  'j', 'J', 'k', 'K', 'l', 'L', 'm', 'M', 'n', 'N', 'o', 'O', 'p',
  'P', 'q', 'Q', 'r', 'R', 's', 'S', 't', 'T', 'u', 'U', 'v', 'V',
  'w', 'W', 'x', 'X', 'y', 'Y', 'z', 'Z',
  'җ', 'ә', 'ү', 'ː', 'қ', 'ћ', 'Ä', 'Ҋ', 'ј', 'Ι', 'Χ',
  
  # There is a lot of broken sentences like:
  # У меня щемило сердце: «Что мы сделаем?
  # Такой он был веселый, бодрый, нас воодушевлял: „Вы знаете, не бойтесь!
  # История и культура»".
  # Пушкин, прочитав поэму, сказал «— Далеко мальчик пойдет».
  # После увольнения он пытается создать новую жизнь...Жизнь, в свою очередь, строит ему множество «баррикад"
  # Пушкин, Набоков… мало кого еще можно поставить в этот ряд?
  # Let's remove them all, we have so many good sentences without problems
  '«', '»', '"', '„', '“', '”', '‘', '…',
  
  '{', '}', '（', '）',
  
  # Sentences with accented chars, it is not possible to voice and
  # should be removed, example:
  # е́р
  'ѣ', 'Ѣ', 'І', 'ң', 'ă', 'ĕ', ' ́', '́',
  
  # Sentences with invisible chars
  '­', '​', '﻿', '་',
]

broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;", " \""]

# Abbreviations:
# 1. М.Н.С.
# 2. А. Пушкин
# 3. Дж.
# 4. СССР
# 5. г. Пушкина.
# 6. — —
# 7. сайка фито— и зоопланктоном
# 8. Повод —первое упоминание
# 9. с разрывом связей С—С и образованием
# 10. ор. ок.
# 11. по учению св.отцов
# 12. др.-евр. чл.-корр.
# 13. ул.Тюменская
# 14. Ставропольский кр.,

# It is not possible to disallow ALL bad symbols, let's use regex for this
# 15. Remove any other bad symbols
abbreviation_patterns = [
  "[А-Я]+\\.*[А-Я]",
  "[А-Я]\\.",
  "[А-Я][а-я]\\.",
  "[А-Я]{2,}",
  "\\s[а-я]\\.",
  "— —",
  "[а-я]—\\s[а-я]",
  "[а-я]\\s—[а-я]",
  "[А-Я]—[А-Я]",
  "\\s(ор|ок|ом|ум|те|ил)\\.",
  "[а-я]\\.[а-я]",
  "[а-я]{1,3}\\.-[а-я]{1,4}\\.",
  "[А-Яа-я]\\.[А-Яа-я]",
  "\\.,",
  "[^\\dА-Яа-яёЁ\\s:,.-‑?;!—­‐–'·=’―−”‘]"
]
