min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_characters = 3
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = true
needs_uppercase_start = true
disallowed_symbols = ['"', '<', '>', '+', '*', '\\', '#', '@', '^', '[', ']', '(', ')', '/', '«', '»',]
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;", ", ',", " :","¿ ","¡ "]
abbreviation_patterns = ["[A-Z]+\\.*[A-Z]", "[A-Z]\\.$"]
