language: rust
dist: bionic
rust: nightly
cache: cargo

install: cargo build --release

before_script:
  - rustup component add clippy

script:
  - cargo test --verbose
  - cargo clippy --all-targets --all-features
