# Default on every push and PR

name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]

    steps:
    
    # SETUP
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@v1.3.4
      with:
        rust-version: ${{ matrix.rust }}
        components: clippy
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # TESTS
    - name: Run clippy
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose