# Runs on every change on a PR, this can be used to validate
# the rule file changes using an extracted sample.

name: Pull Request Changes

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  extract:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    
    # SETUP
    - uses: hecrj/setup-rust-action@e0938bab41405f7485391869b453779c5290099d
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    
    # GET CHANGED FILES TO DETERMINE LANGUAGE
    - name: Get Commit Message
      run: echo "COMMIT_MESSAGE=\"$(git log --format=%B -n 1 ${{ github.event.after }})\"" >> $GITHUB_ENV
    - uses: futuratrepadeira/changed-files@b4ef6fe532b9b5022be2489df114ba28146aea14
      id: files
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    # EXTRACTION
    - name: Sample Wikipedia Extraction
      run: ./scripts/extraction.sh
      env:
        FILES_CREATED: ${{ steps.files.outputs.files_created }}
        FILES_UPDATED: ${{ steps.files.outputs.files_updated }}
    - name: Deduplicate Wikipedia Extraction
      run: ./scripts/dedupe.sh extract.txt

    # UPLOAD  
    - uses: actions/upload-artifact@v2
      with:
        name: extraction
        path: output/*
    - uses: actions/upload-artifact@v2
      with:
        name: wikiextractor-output
        path: text/*
